### ISSUE TITLE
Clicking Open docs link getting 404 error

### ISSUE THREAD

**Issue by vinoth-html** [on-org/nuxt-openapi-docs-module#23]
I have done local setup, after clicking open docs link, I'm getting 404 error.

Path: docs/ not working. Please advise.

**Comment by s00d** [comment]
docs path work only with [list](https://github.com/on-org/nuxt-openapi-docs-module/blob/77b06118f741baed45db7db896fcfaabd2a773f8/playground/nuxt.config.ts#L45) param

look at the example in the [playground](https://github.com/on-org/nuxt-openapi-docs-module/tree/main/playground) folder, if you don't need a list, you can just view the new routes in [devtools](https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)

**Comment by vinoth-html** [comment]
In my case list is true. Still /docs not working. I could not see list. Please advise.

**Comment by s00d** [comment]
Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)?

**Comment by s00d** [comment]
[Here's](https://stackblitz.com/edit/github-j7idul?file=README.md) a simple example added, and also fixed the work without i18n
